---
#partner repo
- name: partner repository
  apt_repository: repo='deb http://archive.canonical.com/ubuntu trusty partner'
  sudo: yes
- name: partner repository (src)
  apt_repository: repo='deb-src http://archive.canonical.com/ubuntu trusty partner'
  sudo: yes
#extras repo
- name: extra repository
  apt_repository: repo='deb http://extras.ubuntu.com/ubuntu trusty main'
  sudo: yes
- name: extra repository (src)
  apt_repository: repo='deb-src http://extras.ubuntu.com/ubuntu trusty main'
  sudo: yes

#fix the osd-notify - http://askubuntu.com/questions/367961/no-notifications-from-notify-osd-on-13-10
- name: check if notify-daemon exists
  stat: path=/etc/xdg/autostart/notification-daemon.desktop
  register: notify_daemon_stat
- name: Fix osd-notify
  lineinfile: state=present dest=/etc/xdg/autostart/notification-daemon.desktop line=OnlyShowIn=Unity; regexp='OnlyShowIn.*' backup=yes
  sudo: true
  when: notify_daemon_stat.stat.exists

# remove ibus ctrl+space binding
- name: fix ibus keybinding
  command: gsettings set org.freedesktop.ibus.general.hotkey triggers '[]'
