---
- name: check for docker
  stat: path="/usr/bin/docker"
  register: st
- name: ensure wget for docker
  apt: name=wget
  sudo: true
  when: not st.stat.exists
- name: install docker
  shell: wget -qO- https://get.docker.com/ | sh
  sudo: true
  when: not st.stat.exists
- name: Disable sudo only access to docker
  command: usermod -aG docker filho
  sudo: true
  when: not st.stat.exists
