#clean out some stuff
- include: clean_packages.yml
  sudo: yes

#standard packages
- include: std_packages.yml
  sudo: true

#git config
- include: _git_config.yml

#chrome
- name: See if chrome is installed
  command: find /usr/bin -name 'google-chrome'
  register: chrome_installed
- include: _google_chrome.yml
  when: (not chrome_installed.stdout)

- include: docker.yml

- include: install_java.yml

- include: jdownloader.yml
