#clean out some stuff
- include: clean_packages.yml
  become: true

# Java first, so it fails fast
- include: install_java.yml

#standard packages
- include: std_packages.yml
  become: true

#git config
- include: _git_config.yml

#chrome
- name: See if chrome is installed
  command: find /usr/bin -name 'google-chrome'
  register: chrome_installed
- include: _google_chrome.yml
  when: (not chrome_installed.stdout)

- include: docker.yml

- include: jdownloader.yml

- include: virtualbox.yml
