# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# theme
ZSH_THEME="cloud"

#plugins
plugins=(vagrant git ubuntu git-extras colored-man autojump go zsh_reload dirhistory zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

if [ -f ~/.dircolors ]; then
  eval `dircolors ~/.dircolors`
fi

#yes, I suck.
export EDITOR='nano -w'